version: "3.9"

services:
  ci:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "teamcity"
    image: "docker-teamcity-image"
    privileged: true
    ports:
      - "8111:8111"
    restart: always
    volumes:
      - ./data:/opt/TeamCity
